version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations/up_001.sql:/docker-entrypoint-initdb.d/up_001.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10  

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8888:8888"
    env_file:
      - .env

volumes:
  db_data: